// ── Module Presets ────────────────────────────────────────────────
export const PRESETS_MODULES: Record<string, Array<Record<string, unknown>>> = {
  'hakikat-norma': [
    {
      type: 'petunjuk',
      title: 'Cara Menggunakan Media Ini',
      intro: 'Ikuti langkah-langkah berikut agar pembelajaran berjalan optimal',
      langkah: [
        { icon: '\uD83C\uDFAD', judul: 'Skenario Interaktif', isi: 'Hadapi 4 situasi nyata. Setiap pilihan punya konsekuensi — temukan sendiri kaitannya dengan norma!' },
        { icon: '\uD83D\uDCD6', judul: 'Baca & Eksplorasi', isi: 'Pelajari pengertian dan fungsi norma. Tandai tiap tab setelah dibaca agar tidak ada yang terlewat!' },
        { icon: '\uD83D\uDCAC', judul: 'Diskusi & Tulis', isi: 'Jawab pertanyaan diskusi — jawabanmu otomatis tersimpan dan akan tampil lagi di Refleksi sebagai portofoliomu' },
        { icon: '\uD83C\uDFAE', judul: 'Game Fungsi Norma', isi: 'Uji pemahamanmu dengan 5 soal benar-salah. Setiap jawaban benar memberi penjelasan mendalam!' },
      ],
    },
    {
      type: 'tab-icons',
      title: '5 Fungsi Norma',
      intro: 'Eksplorasi 5 fungsi norma dalam kehidupan bermasyarakat',
      layout: 'horizontal',
      animation: 'fade',
      tabs: [
        { icon: '\uD83D\uDDFA\uFE0F', judul: 'Pedoman', warna: '#f9c82e', isi: 'Norma memberi petunjuk kepada setiap individu tentang cara bertindak yang baik dan benar dalam pergaulan sehari-hari.', poin: ['Mengajarkan cara bertindak yang baik', 'Memberi tahu apa yang boleh dan tidak boleh', 'Panduan perilaku dalam situasi sosial'], refleksi: 'Sebutkan 1 norma yang selama ini menjadi panduan perilakumu di sekolah!' },
        { icon: '\uD83E\uDD1D', judul: 'Ketertiban', warna: '#3ecfcf', isi: 'Norma mencegah kekacauan dan konflik. Dengan norma, setiap orang tahu apa yang boleh dan tidak boleh dilakukan sehingga kehidupan berjalan teratur.', poin: ['Mencegah kekacauan dan konflik', 'Setiap orang tahu batasnya', 'Kehidupan berjalan teratur dan dapat diprediksi'], refleksi: 'Bayangkan jika tidak ada aturan di kelasmu — apa yang akan terjadi dalam 1 jam pelajaran?' },
        { icon: '\uD83D\uDEE1\uFE0F', judul: 'Melindungi Hak', warna: '#ff6b6b', isi: 'Norma menjamin setiap anggota masyarakat mendapatkan hak-haknya dan diperlakukan secara adil tanpa diskriminasi.', poin: ['Menjamin hak setiap orang', 'Mencegah perampasan hak', 'Perlindungan tanpa diskriminasi'], refleksi: 'Hak apa yang kamu rasakan paling terlindungi oleh norma di lingkunganmu?' },
        { icon: '\uD83D\uDC9A', judul: 'Solidaritas', warna: '#34d399', isi: 'Norma mempererat rasa kebersamaan, persatuan, dan kepedulian antaranggota masyarakat. Norma mengajarkan bahwa kita saling membutuhkan satu sama lain.', poin: ['Mempererat kebersamaan', 'Mengajarkan kepedulian sosial', 'Membangun gotong royong'], refleksi: 'Contoh kegiatan gotong royong apa yang masih ada di lingkunganmu saat ini?' },
        { icon: '\u2696\uFE0F', judul: 'Keadilan', warna: '#a78bfa', isi: 'Norma memastikan setiap orang diperlakukan setara dan adil. Tidak ada yang boleh mendapat perlakuan berbeda hanya karena kekayaan, jabatan, atau kekuasaan.', poin: ['Setiap orang diperlakukan setara', 'Tidak ada diskriminasi', 'Hukum berlaku sama untuk semua'], refleksi: 'Pernahkah kamu melihat ketidakadilan di sekitarmu? Norma apa yang seharusnya ditegakkan?' },
      ],
    },
    {
      type: 'flashcard',
      title: 'Kartu Kilat: Hakikat Norma',
      instruksi: 'Ketuk kartu untuk melihat jawaban. Uji ingatanmu!',
      kartu: [
        { depan: 'Apa definisi norma?', belakang: 'Aturan atau ketentuan yang mengikat warga masyarakat, dipakai sebagai panduan, tatanan, dan pengendali tingkah laku.' },
        { depan: 'Mengapa manusia disebut Zoon Politikon?', belakang: 'Karena manusia selalu hidup berkelompok dan tidak bisa memenuhi kebutuhannya seorang diri — ia selalu membutuhkan orang lain.' },
        { depan: 'Sebutkan 4 kata kunci sifat norma!', belakang: 'Mengikat — Panduan — Tatanan — Pengendali' },
        { depan: 'Bagaimana proses lahirnya norma?', belakang: 'Manusia hidup bersama → timbul perbedaan kepentingan → muncul kebutuhan aturan → norma terbentuk dari adat, kesepakatan, agama, atau undang-undang.' },
        { depan: 'Apa fungsi norma sebagai pedoman tingkah laku?', belakang: 'Norma memberi petunjuk tentang cara bertindak yang baik dan benar dalam pergaulan — apa yang boleh, tidak boleh, dan harus dilakukan.' },
        { depan: 'Bagaimana norma melindungi hak warga?', belakang: 'Norma menjamin setiap anggota masyarakat mendapatkan haknya dan diperlakukan adil — tidak ada yang boleh merampas hak orang lain.' },
      ],
    },
    {
      type: 'truefalse',
      title: 'Game: Fungsi Norma',
      instruksi: 'Tentukan benar atau salah pernyataan berikut tentang fungsi norma!',
      soal: [
        { teks: 'Norma hanya berfungsi sebagai larangan', jawaban: false, penjelasan: 'Norma bukan hanya larangan — ia juga berfungsi sebagai pedoman, pelindung hak, pemersatu, dan penegak keadilan.' },
        { teks: 'Gotong royong adalah contoh norma yang memperkuat solidaritas', jawaban: true, penjelasan: 'Gotong royong mempererat rasa kebersamaan dan kepedulian antarwarga.' },
        { teks: 'Norma hukum berlaku berbeda untuk orang kaya dan miskin', jawaban: false, penjelasan: 'Norma hukum memastikan semua orang diperlakukan setara — kaya atau miskin.' },
        { teks: 'Norma kesopanan menciptakan ketertiban dalam masyarakat', jawaban: true, penjelasan: 'Dengan norma, setiap orang tahu apa yang boleh dan tidak boleh dilakukan sehingga tercipta ketertiban.' },
        { teks: 'Pelanggaran norma tidak memiliki konsekuensi apapun', jawaban: false, penjelasan: 'Setiap norma memiliki sanksi — mulai dari rasa bersalah (internal) hingga hukuman resmi (eksternal).' },
      ],
    },
    {
      type: 'diskusi',
      title: 'Diskusi Kelas',
      intro: 'Jawab pertanyaan berikut — jawabanmu akan tersimpan untuk portofolio refleksi',
      pertanyaan: [
        { label: 'Diskusi Makhluk Sosial', icon: '\uD83D\uDCAC', teks: 'Bayangkan kamu tinggal di sebuah pulau bersama 30 orang yang tidak saling mengenal, tanpa pemimpin dan tanpa aturan sama sekali. Apa yang akan terjadi dalam 1 minggu pertama? Apa masalah yang paling pertama muncul?', petunjuk: 'Jawabanmu akan tampil lagi di Refleksi sebagai portofoliomu' },
        { label: 'Latihan Mandiri', icon: '\u270D\uFE0F', teks: 'Dengan kata-katamu sendiri, jelaskan apa yang dimaksud norma dan mengapa norma dibutuhkan. Gunakan contoh dari kehidupan sehari-harimu!', petunjuk: 'Gunakan pengalaman pribadimu sebagai contoh' },
      ],
    },
    {
      type: 'refleksi',
      title: 'Refleksi Akhir',
      intro: 'Tuliskan refleksimu tentang pembelajaran hari ini',
      pertanyaan: [
        { teks: 'Apa yang paling kamu pelajari hari ini tentang hakikat norma?', petunjuk: 'Tulis 2-3 hal yang paling berkesan' },
        { teks: 'Bagaimana kamu akan menerapkan pemahaman tentang norma dalam kehidupan sehari-hari?', petunjuk: 'Tulis rencana aksi nyata yang bisa kamu lakukan' },
      ],
    },
  ],
  'macam-norma': [
    {
      type: 'petunjuk',
      title: 'Cara Belajar Hari Ini',
      intro: 'Setiap aktivitas dilengkapi panduan diskusi dan pertanyaan pemantik',
      langkah: [
        { icon: '\uD83D\uDC65', judul: 'Diskusi Kelompok', isi: 'Setiap aktivitas dilengkapi panduan diskusi dan pertanyaan pemantik. Diskusikan dulu sebelum menjawab!' },
        { icon: '\uD83D\uDE4F', judul: '4 Jenis Norma', isi: 'Pelajari kartu detail setiap norma. Bagi tugas membaca antar anggota kelompok!' },
        { icon: '\uD83D\uDD1F', judul: 'Game Sortir Norma', isi: 'Klasifikasikan 12 perilaku ke jenis norma yang tepat. Diskusi kelompok dulu sebelum menjawab!' },
        { icon: '\uD83C\uDFA1', judul: 'Roda Norma', isi: 'Putar roda dan jawab pertanyaan tentang macam-macam norma!' },
      ],
    },
    {
      type: 'review',
      title: 'Ingat Kembali Pertemuan 1',
      intro: 'Apa saja yang sudah dipelajari dan apa yang akan dipelajari hari ini?',
      kartu: [
        { icon: '\u2705', judul: 'Sudah dipelajari', isi: '\u2022 Manusia = makhluk sosial\n\u2022 Norma = aturan mengikat\n\u2022 5 fungsi norma', warna: '#34d399' },
        { icon: '\uD83C\uDFAF', judul: 'Hari ini', isi: '\u2022 4 jenis norma & sumbernya\n\u2022 Sanksi tiap norma\n\u2022 Hubungan antarnorma', warna: '#3ecfcf' },
      ],
    },
    {
      type: 'icon-explore',
      title: '4 Jenis Norma',
      intro: 'Klik ikon untuk mempelajari setiap jenis norma secara mendalam',
      layout: 'grid',
      animation: 'fade',
      items: [
        { icon: '\uD83D\uDE4F', judul: 'Norma Agama', warna: '#f9c82e', ringkasan: 'Norma dari Tuhan melalui kitab suci', isi: 'Norma agama berasal dari Tuhan Yang Maha Esa melalui kitab suci. Bersifat universal bagi pemeluknya, mengatur hubungan vertikal (dengan Tuhan) dan horizontal (sesama manusia). Sanksinya berupa dosa dan rasa bersalah batin.', contoh: ['Shalat lima waktu bagi Muslim', 'Berdoa sebelum makan', 'Tidak berbohong karena Tuhan Maha Mengetahui'], sanksi: 'Dosa di akhirat, rasa bersalah batin, sanksi sosial keagamaan' },
        { icon: '\u2764\uFE0F', judul: 'Norma Kesusilaan', warna: '#ff6b6b', ringkasan: 'Norma dari hati nurani manusia', isi: 'Norma kesusilaan berasal dari hati nurani manusia — nilai baik-buruk yang dirasakan naluriah. Bersifat universal, tidak tertulis, dan tidak bisa dipaksakan dari luar. Sanksinya berupa rasa bersalah dan malu dari dalam diri sendiri.', contoh: ['Mengembalikan dompet yang ditemukan', 'Jujur meski tidak ada yang tahu', 'Tidak menyontek karena hati nurani'], sanksi: 'Rasa bersalah, rasa malu, dikucilkan lingkungan' },
        { icon: '\uD83E\uDD1D', judul: 'Norma Kesopanan', warna: '#3ecfcf', ringkasan: 'Norma dari adat istiadat masyarakat', isi: 'Norma kesopanan berasal dari adat istiadat dan kebiasaan masyarakat secara turun-temurun. Berbeda-beda antar daerah, tidak tertulis, tapi sangat kuat pengaruhnya secara sosial. Sanksinya berupa teguran dan pengucilan sosial.', contoh: ['Mengucap salam saat bertemu', 'Membungkuk saat melewati orang lebih tua', 'Tidak memotong pembicaraan orang lain'], sanksi: 'Ditegur, dicela, dijauhi, dikucilkan' },
        { icon: '\u2696\uFE0F', judul: 'Norma Hukum', warna: '#a78bfa', ringkasan: 'Norma dari negara, tertulis dan tegas', isi: 'Norma hukum berasal dari negara/lembaga resmi berwenang. Bersifat tertulis, tegas, berlaku bagi seluruh warga negara tanpa pengecualian, dan ada aparat penegak hukum. Sanksinya berupa denda, penjara, atau pencabutan hak.', contoh: ['Larangan mencuri (KUHP)', 'Wajib menggunakan helm saat berkendara', 'Membayar pajak sesuai penghasilan'], sanksi: 'Denda, penjara, pencabutan hak oleh negara' },
      ],
    },
    {
      type: 'sorting',
      title: 'Game Sortir Norma',
      instruksi: 'Klasifikasikan setiap perilaku ke jenis norma yang tepat!',
      kategori: [
        { label: 'Norma Agama', color: '#f9c82e', id: 'agama' },
        { label: 'Norma Kesusilaan', color: '#ff6b6b', id: 'kesusilaan' },
        { label: 'Norma Kesopanan', color: '#3ecfcf', id: 'kesopanan' },
        { label: 'Norma Hukum', color: '#a78bfa', id: 'hukum' },
      ],
      items: [
        { teks: 'Berdoa sebelum makan', kategori: 'agama' },
        { teks: 'Mengembalikan dompet yang ditemukan', kategori: 'kesusilaan' },
        { teks: 'Mengucap salam saat bertemu guru', kategori: 'kesopanan' },
        { teks: 'Tidak mencuri karena dilarang UU', kategori: 'hukum' },
        { teks: 'Tidak mencontek karena dosa', kategori: 'agama' },
        { teks: 'Jujur meski tidak ada yang tahu', kategori: 'kesusilaan' },
        { teks: 'Tidak memutar musik keras di perumahan', kategori: 'kesopanan' },
        { teks: 'Membayar pajak tepat waktu', kategori: 'hukum' },
        { teks: 'Berpuasa di bulan Ramadhan', kategori: 'agama' },
        { teks: 'Membantu korban kecelakaan tanpa pamrih', kategori: 'kesusilaan' },
        { teks: 'Minta maaf saat bersalah', kategori: 'kesopanan' },
        { teks: 'Memakai helm saat naik motor', kategori: 'hukum' },
      ],
    },
    {
      type: 'roda',
      title: 'Roda Norma',
      instruksi: 'Putar roda dan jawab pertanyaan tentang norma!',
      opsi: [
        '\uD83D\uDE4F Agama',
        '\u2764\uFE0F Kesusilaan',
        '\uD83E\uDD1D Kesopanan',
        '\u2696\uFE0F Hukum',
      ],
      soal: [
        { teks: 'Norma yang sanksinya berupa dosa dan hukuman akhirat', jawaban: '\uD83D\uDE4F Agama' },
        { teks: 'Norma yang berasal dari adat istiadat masyarakat', jawaban: '\uD83E\uDD1D Kesopanan' },
        { teks: 'Norma yang bersifat tertulis dan ada aparat penegaknya', jawaban: '\u2696\uFE0F Hukum' },
        { teks: 'Norma yang berasal dari hati nurani manusia', jawaban: '\u2764\uFE0F Kesusilaan' },
        { teks: 'Contoh: berdoa sebelum makan', jawaban: '\uD83D\uDE4F Agama' },
        { teks: 'Contoh: mengucap salam saat bertemu guru', jawaban: '\uD83E\uDD1D Kesopanan' },
      ],
    },
    {
      type: 'comparison',
      title: 'Hubungan Antarnorma',
      intro: 'Norma-norma tidak berdiri sendiri — mereka saling terkait dan memengaruhi satu sama lain',
      animation: 'fade',
      kolom: [
        { icon: '\uD83D\uDE4F', judul: 'Norma Agama', warna: '#f9c82e' },
        { icon: '\u2696\uFE0F', judul: 'Norma Hukum', warna: '#a78bfa' },
      ],
      baris: [
        { label: 'Sumber', icon: '\uD83D\uDCCC', nilai: ['Tuhan / Kitab Suci', 'Negara / UU'] },
        { label: 'Sifat', icon: '\u2699\uFE0F', nilai: ['Universal bagi pemeluknya', 'Mengikat seluruh warga negara'] },
        { label: 'Sanksi', icon: '\u26A0\uFE0F', nilai: ['Dosa & sanksi akhirat', 'Denda, penjara, pencabutan hak'] },
        { label: 'Contoh', icon: '\uD83D\uDCA1', nilai: ['Shalat, berdoa, jujur', 'Membayar pajak, taat UU'] },
      ],
      tanya: 'Bagaimana hubungan antara norma agama dan norma hukum di Indonesia?',
    },
    {
      type: 'flashcard',
      title: 'Kartu Kilat: Macam-Macam Norma',
      instruksi: 'Ketuk kartu untuk melihat jawaban. Uji ingatanmu!',
      kartu: [
        { depan: 'Apa sumber norma agama?', belakang: 'Tuhan Yang Maha Esa melalui kitab suci dan wahyu. Bersifat universal bagi pemeluk agama tersebut.' },
        { depan: 'Apa sanksi pelanggaran norma kesusilaan?', belakang: 'Rasa bersalah dan malu dari dalam diri sendiri. Sanksi bersifat internal karena berasal dari hati nurani.' },
        { depan: 'Mengapa norma kesopanan berbeda antar daerah?', belakang: 'Karena norma kesopanan berasal dari adat istiadat dan kebiasaan masyarakat yang berbeda-beda di setiap daerah.' },
        { depan: 'Apa yang membedakan norma hukum dari norma lainnya?', belakang: 'Norma hukum bersifat tertulis, tegas, berlaku bagi seluruh warga negara, dan ada aparat penegak hukum dengan sanksi denda/penjara.' },
        { depan: 'Berikan contoh hubungan antara norma agama dan hukum!', belakang: 'Di Indonesia, norma agama melarang mencuri dan norma hukum juga mengaturnya dalam KUHP. Keduanya saling memperkuat.' },
        { depan: 'Norma apa yang sanksinya paling tegas dan mengikat?', belakang: 'Norma Hukum — sanksinya berupa denda, penjara, atau pencabutan hak oleh negara melalui aparat penegak hukum.' },
      ],
    },
    {
      type: 'diskusi',
      title: 'Diskusi Kelompok',
      intro: 'Diskusikan pertanyaan berikut bersama kelompokmu',
      pertanyaan: [
        { label: 'Diskusi Perbandingan Norma Keluarga', icon: '\uD83D\uDCDD', teks: 'Tuliskan 1-2 temuan menarik dari perbandingan tabel norma keluarga kelompokmu. Norma apa yang sama? Norma apa yang unik/berbeda?', petunjuk: 'Jawabanmu akan tampil lagi di Refleksi' },
        { label: 'Diskusi Hubungan Antarnorma', icon: '\uD83D\uDCAC', teks: 'Setelah semua presentasi: Norma mana yang paling berbeda dari yang kamu bayangkan sebelumnya? Mengapa sanksinya berbeda antar norma?', petunjuk: 'Diskusikan bersama kelompokmu' },
      ],
    },
    {
      type: 'refleksi',
      title: 'Refleksi Akhir',
      intro: 'Tuliskan refleksimu tentang pembelajaran hari ini',
      pertanyaan: [
        { teks: 'Norma mana yang paling sering kamu jumpai dalam kehidupan sehari-hari? Berikan contohnya!', petunjuk: 'Pikirkan norma yang kamu temui di rumah, sekolah, dan masyarakat' },
        { teks: 'Mengapa keempat jenis norma saling melengkapi? Apa yang terjadi jika hanya ada satu jenis norma?', petunjuk: 'Gunakan contoh dari diskusi sebelumnya' },
      ],
    },
  ],
  'perilaku-patuhan': [
    {
      type: 'petunjuk',
      title: 'Cara Belajar Hari Ini',
      intro: 'Pertemuan terakhir Bab 3 — saatnya menerapkan semua yang sudah dipelajari!',
      langkah: [
        { icon: '\uD83D\uDD04', judul: 'Review P1 & P2', isi: 'Kilas balik hakikat norma dan macam-macam norma. Siapkan diri untuk menerapkan!' },
        { icon: '\uD83C\uDFE0', judul: 'Eksplorasi 4 Lingkungan', isi: 'Pelajari penerapan norma di keluarga, sekolah, masyarakat, dan negara melalui tab interaktif.' },
        { icon: '\uD83D\uDCDD', judul: 'Kuis & Diskusi Kasus', isi: 'Kuis 10 soal tentang seluruh Bab 3, lalu diskusi kelompok analisis kasus konflik norma.' },
        { icon: '\uD83D\uDCAA', judul: 'Refleksi & Komitmen', isi: 'Tulis komitmen pribadi dan tandatangani "Deklarasi Patuh Norma" secara simbolis.' },
      ],
    },
    {
      type: 'review',
      title: 'Ingat Kembali Pertemuan 1 & 2',
      intro: 'Apa saja yang sudah dipelajari dan apa yang akan dipelajari hari ini?',
      kartu: [
        { icon: '\u2705', judul: 'Pertemuan 1 — Hakikat Norma', isi: '\u2022 Manusia = makhluk sosial\n\u2022 Norma = aturan mengikat\n\u2022 5 fungsi norma', warna: '#34d399' },
        { icon: '\u2705', judul: 'Pertemuan 2 — Macam-Macam Norma', isi: '\u2022 4 jenis norma & sumbernya\n\u2022 Sanksi tiap norma\n\u2022 Hubungan antarnorma', warna: '#3ecfcf' },
        { icon: '\uD83C\uDFAF', judul: 'Hari ini — Perilaku Patuh', isi: '\u2022 Penerapan norma di 4 lingkungan\n\u2022 Budaya patuh norma\n\u2022 Komitmen pribadi', warna: '#f9c82e' },
      ],
    },
    {
      type: 'tab-icons',
      title: 'Penerapan Norma di 4 Lingkungan',
      intro: 'Eksplorasi bagaimana norma diterapkan dalam berbagai lingkungan kehidupan',
      layout: 'horizontal',
      animation: 'fade',
      tabs: [
        { icon: '\uD83C\uDFE0', judul: 'Keluarga', warna: '#f9c82e', isi: 'Di lingkungan keluarga, norma mengatur hubungan antar anggota keluarga. Norma agama mewarnai nilai-nilai keluarga, norma kesusilaan menjadi dasar kasih sayang, norma kesopanan mengatur tata krama, dan norma hukum melindungi hak-hak anggota keluarga.', poin: ['Menghormati dan membantu orang tua', 'Berkomunikasi dengan sopan dalam keluarga', 'Menjalankan tradisi dan nilai keluarga'], refleksi: 'Norma apa yang paling kuat di keluargamu? Beri contohnya!' },
        { icon: '\uD83C\uDFEB', judul: 'Sekolah', warna: '#3ecfcf', isi: 'Di lingkungan sekolah, norma diterapkan melalui tata tertib, etika belajar, dan hubungan antar warga sekolah. Norma hukum berupa peraturan sekolah, norma kesopanan mengatur etika bergaul, norma agama melalui kegiatan keagamaan, dan norma kesusilaan menjadi dasar kejujuran.', poin: ['Mematuhi tata tertib sekolah', 'Menghormati guru dan teman', 'Jujur dalam ulangan dan tugas'], refleksi: 'Norma mana yang paling sering kamu patuhi di sekolah?' },
        { icon: '\uD83C\uDFD8\uFE0F', judul: 'Masyarakat', warna: '#34d399', isi: 'Di lingkungan masyarakat, norma berupa adat istiadat, gotong royong, dan peraturan daerah. Norma kesopanan paling menonjol dalam kehidupan bermasyarakat, diikuti norma hukum berupa peraturan daerah dan norma agama dalam kegiatan keagamaan komunal.', poin: ['Ikut gotong royong dan kegiatan sosial', 'Menghormati tetangga dan perbedaan', 'Mematuhi peraturan daerah setempat'], refleksi: 'Kegiatan gotong royong apa yang masih ada di lingkunganmu?' },
        { icon: '\uD83C\uDDEE\uD83C\uDDE9', judul: 'Negara', warna: '#a78bfa', isi: 'Dalam kehidupan berbangsa dan bernegara, norma hukum menjadi paling menonjol melalui UUD dan undang-undang. Norma agama memengaruhi hukum nasional, norma kesusilaan menjadi dasar kebijakan publik, dan norma kesopanan tercermin dalam etika berdemokrasi.', poin: ['Mematuhi undang-undang dan peraturan negara', 'Membayar pajak sebagai kewajiban warga negara', 'Menghormati lambang dan simbol negara'], refleksi: 'Sebagai warga negara, norma apa yang paling kamu rasakan manfaatnya?' },
      ],
    },
    {
      type: 'debat',
      title: 'Debat: Prioritas Norma',
      pertanyaan: 'Apakah norma hukum harus selalu diprioritaskan di atas norma lainnya?',
      konteks: 'Di Indonesia, norma agama dan hukum sering berjalan beriringan. Namun, kadang terjadi konflik antar norma — mana yang harus diutamakan?',
      pihakA: { label: 'Pro — Norma hukum harus diprioritaskan' },
      pihakB: { label: 'Kontra — Norma lain setara dan kontekstual' },
    },
    {
      type: 'truefalse',
      title: 'Game: Penerapan Norma',
      instruksi: 'Tentukan benar atau salah pernyataan berikut tentang penerapan norma!',
      soal: [
        { teks: 'Membantu orang tua sukarela adalah penerapan norma kesusilaan di keluarga', jawaban: true, penjelasan: 'Membantu sukarela tanpa paksaan menunjukkan hati nurani yang baik — penerapan norma kesusilaan.' },
        { teks: 'Norma hukum hanya berlaku di pengadilan, bukan di sekolah', jawaban: false, penjelasan: 'Tata tertib sekolah adalah bagian dari norma hukum — peraturan tertulis yang berlaku di lingkungan sekolah.' },
        { teks: 'Gotong royong adalah wujud penerapan norma kesopanan di masyarakat', jawaban: true, penjelasan: 'Gotong royong mencerminkan adat kebiasaan tolong-menolong — penerapan norma kesopanan.' },
        { teks: 'Pelanggaran norma tidak berdampak pada kehidupan bermasyarakat', jawaban: false, penjelasan: 'Pelanggaran norma merusak kepercayaan, keharmonisan, dan ketertiban masyarakat.' },
        { teks: 'Menepati janji tanpa pengawasan menunjukkan kepatuhan pada norma kesusilaan', jawaban: true, penjelasan: 'Hanya hati nurani yang mengawasi — inilah penerapan tertinggi norma kesusilaan.' },
      ],
    },
    {
      type: 'flashcard',
      title: 'Kartu Kilat: Penerapan Norma',
      instruksi: 'Ketuk kartu untuk melihat jawaban. Uji ingatanmu!',
      kartu: [
        { depan: 'Contoh norma di keluarga?', belakang: 'Membantu orang tua, menghormati kakak/adik, berdoa bersama, komunikasi sopan.' },
        { depan: 'Mengapa tata tertib sekolah termasuk norma hukum?', belakang: 'Karena tertulis, berlaku bagi semua siswa, dan ada sanksi jika dilanggar — ciri-ciri norma hukum.' },
        { depan: 'Apa itu budaya patuh norma?', belakang: 'Kebiasaan masyarakat untuk secara sukarela mematuhi norma tanpa paksaan — karena kesadaran, bukan takut sanksi.' },
        { depan: 'Mengapa gotong royong penting dalam penerapan norma?', belakang: 'Gotong royong adalah wujud nyata penerapan norma kesopanan dan solidaritas — tanpa paksaan, dari kesadaran bersama.' },
        { depan: 'Apa dampak jika masyarakat tidak patuh norma hukum?', belakang: 'Kehilangan ketertiban, keadilan, dan kepastian hukum — kehidupan menjadi kacau dan tidak aman.' },
        { depan: 'Norma apa yang paling sulit dipatuhi? Mengapa?', belakang: 'Norma kesusilaan — karena hanya hati nurani yang mengawasi, tidak ada sanksi eksternal yang memaksa.' },
      ],
    },
    {
      type: 'diskusi',
      title: 'Diskusi Kelas',
      intro: 'Diskusikan pertanyaan berikut tentang penerapan norma dalam kehidupan nyata',
      pertanyaan: [
        { label: 'Diskusi Konflik Norma', icon: '\u2696\uFE0F', teks: 'Bayangkan norma agama dan norma hukum bertentangan dalam satu kasus. Norma mana yang harus diprioritaskan? Berikan alasanmu!', petunjuk: 'Tidak ada jawaban mutlak — yang penting argumentasi yang jelas dan logis' },
        { label: 'Diskusi Penerapan Nyata', icon: '\uD83C\uDFE0', teks: 'Pilih 1 dari 4 lingkungan (keluarga, sekolah, masyarakat, negara). Ceritakan 1 contoh nyata penerapan norma yang kamu lakukan sendiri minggu ini!', petunjuk: 'Gunakan pengalaman pribadimu yang sesungguhnya' },
        { label: 'Diskusi Budaya Patuh', icon: '\uD83D\uDCAA', teks: 'Mengapa budaya patuh norma lebih efektif daripada ketertiban karena takut sanksi? Bagaimana cara membangun budaya patuh di lingkunganmu?', petunjuk: 'Bandingkan kepatuhan karena kesadaran vs kepatuhan karena paksaan' },
      ],
    },
    {
      type: 'refleksi',
      title: 'Refleksi Akhir Bab 3',
      intro: 'Refleksi terakhir — rangkum seluruh pembelajaran 3 pertemuan',
      pertanyaan: [
        { teks: 'Dari 3 pertemuan Bab 3, apa hal paling berkesan yang kamu pelajari tentang norma?', petunjuk: 'Tulis 2-3 hal yang benar-benar mengubah cara pandangmu' },
        { teks: 'Sebutkan 1 contoh nyata di mana kamu MENERAPKAN norma dalam kehidupan sehari-hari tanpa disuruh!', petunjuk: 'Fokus pada tindakan sukarela — bukan karena paksaan' },
        { teks: 'Tulis komitmen pribadimu: 1 tindakan nyata yang akan kamu lakukan sebagai wujud patuh terhadap norma', petunjuk: 'Contoh: Saya akan selalu mengantre dengan tertib dan tidak memotong antrian...' },
      ],
    },
  ],
  blank: [],
};
