// ═══════════════════════════════════════════════════════════════════
// TYPES BARREL — Re-exports everything from sub-modules
// ═══════════════════════════════════════════════════════════════════
// This preserves the public API so `from '../types'` still works.

export type {
  BlockLayout,
  CompressionHints,
  SemanticHints,
  BaseBlock,
  BlockVariant,
  ContainerRef,
  SchemaOperation,
  TransactionResult,
} from './base';

export type {
  CoverBlock,
  HeroBlock,
  PetunjukBlock,
  TpBlock,
  AlurBlock,
  SkenarioBlock,
  DefBoxBlock,
  NcGridBlock,
  FlashcardSetBlock,
  FtabBlock,
  NormaKartuBlock,
  MateriSectionBlock,
  DiskusiBlock,
  KuisBlock,
  SortirGameBlock,
  RodaGameBlock,
  MemoryGameBlock,
  MatchingGameBlock,
  FillBlankGameBlock,
  WordSearchGameBlock,
  TrueFalseGameBlock,
  DragDropGameBlock,
  CrosswordGameBlock,
  TeamBuzzerGameBlock,
  HasilBlock,
  RefleksiBlock,
  PenutupBlock,
  TabelAccordionBlock,
  TujuanDisplayBlock,
  MotivasiBlock,
  RangkumanBlock,
  TabelBlock,
  TimelineBlock,
  CompareBlock,
  GambarBlock,
  RevealBlock,
  ChecklistBlock,
  StatistikBlock,
  StudiBlock,
  MateriBlokBlock,
  MateriBlokTipe,
  MateriContentTab,
  TabIconsBlock,
  AccordionBlock,
  InfografisBlock,
} from './blocks';

export type {
  SchemaBlock,
  TabDefinition,
  ScreenSchema,
  LessonSchema,
} from './schema';
