// ═══════════════════════════════════════════════════════════════════
// SORTIR IMPORT — JSON import validator & mapper for sorting game
// ═══════════════════════════════════════════════════════════════════
// Sprint 2F — Import JSON for Sortir Game
//
// PURPOSE:
//   Teachers can paste/import JSON from external AI tools
//   to populate a sorting game with columns and items at once.
//
// KEY DESIGN DECISION:
//   In the import JSON, pool[].category = kolom label (human-readable).
//   The mapper converts labels to internal kolom.id (nanoid).
//   This follows the principle: "AI only fills data, app makes ids."
//
// FORMAT:
//   {
//     "title": "Sortir Jenis Norma",
//     "kolom": [
//       { "label": "Agama", "color": "y" },
//       { "label": "Hukum", "color": "p" }
//     ],
//     "pool": [
//       { "text": "Berdoa sebelum makan", "category": "Agama" },
//       { "text": "Memakai helm", "category": "Hukum" }
//     ]
//   }
//
// RELATIONSHIP:
//   pool[].category (in JSON) → kolom[].label (matched case-insensitive)
//   pool[].category (in schema) → kolom[].id (nanoid, generated by mapper)
// ═══════════════════════════════════════════════════════════════════

import { nanoid } from 'nanoid';
import { stripJsonFence } from './strip-json-fence';

// ── Types ──────────────────────────────────────────────────────

export interface SortirImportKolom {
  label: string;
  color?: string;
}

export interface SortirImportPoolItem {
  text: string;
  category: string;
}

export interface SortirImportPayload {
  title?: string;
  kolom: SortirImportKolom[];
  pool: SortirImportPoolItem[];
}

export interface SortirImportValidation {
  /** Whether the payload is valid (no errors, warnings are OK) */
  valid: boolean;
  /** Fatal errors — block the apply action */
  errors: string[];
  /** Non-fatal warnings — shown but do not block */
  warnings: string[];
  /** Number of kolom in the payload */
  kolomCount: number;
  /** Number of pool items in the payload */
  poolCount: number;
}

// ── Constants ──────────────────────────────────────────────────

const MIN_KOLOM = 2;
const MAX_KOLOM = 4;
const MIN_POOL = 2;
const MAX_POOL = 8;

// ── Validator ──────────────────────────────────────────────────

/**
 * Validates a parsed SortirImportPayload object.
 * Returns validation result with errors (blocking) and warnings (non-blocking).
 *
 * Key validations:
 *   - kolom: 2–4 items, unique labels (case-insensitive)
 *   - pool: 2–8 items, each category must match a kolom label
 *   - FK integrity: pool[].category → kolom[].label
 */
export function validateSortirImportPayload(data: unknown): SortirImportValidation {
  const errors: string[] = [];
  const warnings: string[] = [];

  // 1. Must be an object
  if (typeof data !== 'object' || data === null || Array.isArray(data)) {
    return { valid: false, errors: ['Format tidak valid: harus berupa objek JSON dengan field "kolom" dan "pool".'], warnings: [], kolomCount: 0, poolCount: 0 };
  }

  const obj = data as Record<string, unknown>;

  // 2. Check `title` if present
  if ('title' in obj && obj.title !== undefined && obj.title !== null) {
    if (typeof obj.title !== 'string') {
      errors.push('Field "title" harus berupa string jika ada.');
    }
  }

  // 3. Check `kolom` field
  if (!('kolom' in obj)) {
    return { valid: false, errors: ['Field "kolom" wajib ada.'], warnings: [], kolomCount: 0, poolCount: 0 };
  }

  if (!Array.isArray(obj.kolom)) {
    return { valid: false, errors: ['Field "kolom" harus berupa array.'], warnings: [], kolomCount: 0, poolCount: 0 };
  }

  const kolom = obj.kolom as unknown[];

  if (kolom.length < MIN_KOLOM) {
    errors.push(`Field "kolom" minimal ${MIN_KOLOM} kategori, ditemukan ${kolom.length}.`);
  }

  if (kolom.length > MAX_KOLOM) {
    errors.push(`Field "kolom" maksimal ${MAX_KOLOM} kategori, ditemukan ${kolom.length}. Kurangi jumlah kolom.`);
  }

  // Validate each kolom item
  const kolomLabelsLower: string[] = [];
  const kolomLabelsOriginal: string[] = [];
  kolom.forEach((k, i) => {
    const prefix = `Kolom ${i + 1}`;

    if (typeof k !== 'object' || k === null || Array.isArray(k)) {
      errors.push(`${prefix}: harus berupa objek dengan field "label".`);
      return;
    }

    const item = k as Record<string, unknown>;

    // label — required, non-empty string
    if (!('label' in item) || typeof item.label !== 'string' || item.label.trim() === '') {
      errors.push(`${prefix}: field "label" wajib diisi (nama kategori tidak boleh kosong).`);
    } else {
      const labelLower = item.label.trim().toLowerCase();
      if (kolomLabelsLower.includes(labelLower)) {
        const firstIdx = kolomLabelsLower.indexOf(labelLower);
        errors.push(`${prefix}: label "${item.label.trim()}" duplikat dengan Kolom ${firstIdx + 1}. Label kolom harus unik.`);
      }
      kolomLabelsLower.push(labelLower);
      kolomLabelsOriginal.push(item.label.trim());
    }

    // color — optional, string if present
    if ('color' in item && item.color !== undefined && item.color !== null && typeof item.color !== 'string') {
      errors.push(`${prefix}: field "color" harus berupa string jika ada.`);
    }
  });

  // 4. Check `pool` field
  if (!('pool' in obj)) {
    return { valid: false, errors: ['Field "pool" wajib ada.'], warnings: [], kolomCount: kolom.length, poolCount: 0 };
  }

  if (!Array.isArray(obj.pool)) {
    return { valid: false, errors: ['Field "pool" harus berupa array.'], warnings: [], kolomCount: kolom.length, poolCount: 0 };
  }

  const pool = obj.pool as unknown[];

  if (pool.length < MIN_POOL) {
    errors.push(`Field "pool" minimal ${MIN_POOL} kartu, ditemukan ${pool.length}.`);
  }

  if (pool.length > MAX_POOL) {
    errors.push(`Field "pool" maksimal ${MAX_POOL} kartu, ditemukan ${pool.length}. Kurangi jumlah kartu atau bagi menjadi beberapa game.`);
  }

  // Validate each pool item
  pool.forEach((p, i) => {
    const prefix = `Kartu ${i + 1}`;

    if (typeof p !== 'object' || p === null || Array.isArray(p)) {
      errors.push(`${prefix}: harus berupa objek dengan field "text" dan "category".`);
      return;
    }

    const item = p as Record<string, unknown>;

    // text — required, non-empty string
    if (!('text' in item) || typeof item.text !== 'string' || item.text.trim() === '') {
      errors.push(`${prefix}: field "text" wajib diisi (teks kartu tidak boleh kosong).`);
    }

    // category — required, string, must match a kolom label
    if (!('category' in item) || typeof item.category !== 'string' || item.category.trim() === '') {
      errors.push(`${prefix}: field "category" wajib diisi (kolom tujuan kartu).`);
    } else {
      const catLower = item.category.trim().toLowerCase();
      if (kolomLabelsLower.length > 0 && !kolomLabelsLower.includes(catLower)) {
        errors.push(`${prefix}: kategori "${item.category.trim()}" tidak cocok dengan kolom manapun. Kolom yang tersedia: ${kolomLabelsOriginal.join(', ')}.`);
      }
    }
  });

  // 5. Warnings: check for kolom without pool items
  if (kolomLabelsLower.length > 0 && pool.length > 0) {
    const usedCategories = new Set<string>();
    pool.forEach((p) => {
      if (typeof p === 'object' && p !== null && !Array.isArray(p)) {
        const item = p as Record<string, unknown>;
        if (typeof item.category === 'string' && item.category.trim() !== '') {
          usedCategories.add(item.category.trim().toLowerCase());
        }
      }
    });

    kolomLabelsOriginal.forEach((label, i) => {
      if (!usedCategories.has(label.toLowerCase())) {
        warnings.push(`Kolom ${i + 1} "${label}" tidak punya kartu. Setiap kolom sebaiknya memiliki minimal 1 kartu.`);
      }
    });
  }

  // 6. Warnings: ideal pool size
  if (pool.length > 0 && pool.length < kolom.length * 2) {
    warnings.push(`Hanya ${pool.length} kartu untuk ${kolom.length} kolom. Idealnya minimal 2 kartu per kolom.`);
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
    kolomCount: kolom.length,
    poolCount: pool.length,
  };
}

// ── Parser ─────────────────────────────────────────────────────

/**
 * Parses raw JSON string into a SortirImportPayload.
 * Returns { data, error } — error is set if JSON is invalid.
 */
export function parseSortirImportJSON(raw: string): { data: SortirImportPayload | null; error: string | null } {
  const trimmed = raw.trim();
  if (trimmed === '') {
    return { data: null, error: 'JSON kosong. Paste JSON sortir di kolom di atas.' };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(stripJsonFence(trimmed));
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    return { data: null, error: `JSON tidak valid: ${msg}` };
  }

  return { data: parsed as SortirImportPayload, error: null };
}

// ── Mapper ─────────────────────────────────────────────────────

export interface SortirImportPatch {
  title?: string;
  kolom: Array<{
    id: string;
    label: string;
    color: string;
  }>;
  pool: Array<{
    id: string;
    text: string;
    category: string;
  }>;
}

/**
 * Maps a validated SortirImportPayload to a patch object
 * that can be applied via applyGuidedSchemaPatch().
 *
 * KEY OPERATION: label→id translation
 *   1. Generate nanoid for each kolom[].id
 *   2. Build label→id map (case-insensitive keys)
 *   3. Generate nanoid for each pool[].id
 *   4. Remap pool[].category from label to the corresponding kolom.id
 *
 * This ensures the FK relationship pool[].category → kolom[].id
 * is valid after import, even though the import JSON uses
 * human-readable labels instead of internal ids.
 */
export function mapSortirImportToPatch(data: SortirImportPayload): SortirImportPatch {
  // 1. Generate ids for kolom, build label→id mapping
  const labelToId = new Map<string, string>();
  const kolomWithIds = data.kolom.map(k => {
    const id = nanoid(6);
    const label = k.label.trim();
    const color = k.color?.trim() || 'y';
    // Map case-insensitive label → id
    labelToId.set(label.toLowerCase(), id);
    return { id, label, color };
  });

  // 2. Map pool items: category label → kolom.id
  const poolWithIds = data.pool.map(p => {
    const id = nanoid(6);
    const text = p.text.trim();
    const categoryLabel = p.category.trim().toLowerCase();
    // Look up the kolom.id for this category label
    const kolomId = labelToId.get(categoryLabel) ?? p.category.trim();
    return { id, text, category: kolomId };
  });

  // 3. Build patch
  const patch: SortirImportPatch = {
    kolom: kolomWithIds,
    pool: poolWithIds,
  };

  if (data.title?.trim()) {
    patch.title = data.title.trim();
  }

  return patch;
}

// ── Sample JSON for "Salin Contoh Format" ──────────────────────

// ── AI Prompt Template for "Salin Prompt AI" ──────────────────

export const SORTIR_AI_PROMPT = `Buatkan permainan sortir (pengelompokan) untuk mata pelajaran [TOPIK] kelas [KELAS] dalam format JSON berikut:

{
  "title": "Sortir [Judul]",
  "kolom": [
    { "label": "Nama Kategori 1", "color": "y" },
    { "label": "Nama Kategori 2", "color": "r" }
  ],
  "pool": [
    { "text": "Item yang dikategorikan", "category": "Nama Kategori 1" }
  ]
}

Aturan:
- "kolom" = 2-4 kategori (wajib)
  - "label" = nama kategori (wajib, string, harus unik)
  - "color" = kode warna (opsional): "y" kuning, "r" merah, "c" cyan, "p" ungu
- "pool" = 2-8 kartu item (wajib)
  - "text" = isi kartu (wajib, string)
  - "category" = nama kategori tujuan (wajib, harus sama persis dengan label kolom)
- "title" = judul game (opsional, string)
- Setiap kolom harus punya minimal 1 kartu
- Jangan tulis teks di luar JSON
- Langsung berikan JSON saja tanpa penjelasan tambahan`;

// ── Sample JSON for "Salin Contoh Format" ──────────────────────

export const SORTIR_IMPORT_SAMPLE: string = JSON.stringify({
  title: 'Sortir Jenis Norma',
  kolom: [
    { label: 'Agama', color: 'y' },
    { label: 'Kesusilaan', color: 'r' },
    { label: 'Kesopanan', color: 'c' },
    { label: 'Hukum', color: 'p' },
  ],
  pool: [
    { text: 'Berdoa sebelum makan', category: 'Agama' },
    { text: 'Merasa malu setelah berbohong', category: 'Kesusilaan' },
    { text: 'Mengucapkan salam saat masuk rumah', category: 'Kesopanan' },
    { text: 'Memakai helm saat berkendara', category: 'Hukum' },
    { text: 'Berpuasa di bulan Ramadan', category: 'Agama' },
    { text: 'Tidak menyontek meski tidak ada pengawas', category: 'Kesusilaan' },
    { text: 'Antre tertib tanpa menyerobot', category: 'Kesopanan' },
    { text: 'Membayar pajak tepat waktu', category: 'Hukum' },
  ],
}, null, 2);
